### ISSUE TITLE
web-deploy not working:  Unable to resolve action `SamKirkland/web-deploy@1.0.0`, unable to find version `1.0.0`

### ISSUE THREAD

**Issue by rk50895** [SamKirkland/web-deploy#1]
The output of update main.yml:

Current runner version: '2.275.1'
Operating System
  Ubuntu
  18.04.5
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20201210.0
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20201210.0/images/linux/Ubuntu1804-README.md
Prepare workflow directory
Prepare all required actions
Getting action download info
Failed to resolve action download info. Error: Unable to resolve action `SamKirkland/web-deploy@1.0.0`, unable to find version `1.0.0`
Retrying in 24.817 seconds
Failed to resolve action download info. Error: Unable to resolve action `SamKirkland/web-deploy@1.0.0`, unable to find version `1.0.0`
Retrying in 12.956 seconds
Error: Failed to resolve action download info.

Content of my main.yaml:

on: push
name: Publish Website
jobs:
  web-deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.1.0
    
    - name: 📂 Sync files
      uses: SamKirkland/web-deploy@1.0.0
      with:
        target-server: sftp.beautique-in.nl
        remote-user: 346741
        remote-key: ${{ secrets.ftp_password }}
        rsync-options: --dry-run --insecure

**Comment by agloeckner** [comment]
same here

**Comment by SamKirkland** [comment]
Sorry guys I haven't actually released this yet! To be honest I didn't expect anyone to find this.

I will add a note on the readme to make this obvious. Sorry for the confusion.

**Comment by dlbone** [comment]
> Sorry guys I haven't actually released this yet! To be honest I didn't expect anyone to find this.

We just love your FTP workflow so much we're waiting for your new SFTP/SSH action.

**Comment by SamKirkland** [comment]
@rk50895  @dlbone @agloeckner I finished up this action & released it to the marketplace over the weekend and have it running on a few websites of mine. Should be in a usable state now. Readme needs some improvement still 😄
