### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by reactmore** [SamKirkland/web-deploy#4]
user@domain.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

is it possible to use rsync with password ?

**Comment by ilovelinux** [comment]
Solved converting private key format from OPENSSH to PEM:
```
ssh-keygen -p -m PEM -N '' -f id_rsa
```
as described [here](https://bugzilla.mindrot.org/show_bug.cgi?id=3233#c1)

Related to https://github.com/openssl/openssl/issues/13443
Bug report: https://bugzilla.mindrot.org/show_bug.cgi?id=3233
